.PHONY : run problem1 problem2 problem3 clean

run: problem1 problem2 problem3
	python problem3.py

problem1:
	python problem1.py

problem2: 
	python problem2.py

problem3: problem1 problem2
	python problem3.py

clean:
	rm *.pyc
